version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123         # Senha do usuário root
      MYSQL_DATABASE: RASPLUS                # Banco criado automaticamente
      MYSQL_USER: walker               # Usuário adicional
      MYSQL_PASSWORD: 123      # Senha do usuário adicional
    ports:
      - "3306:3306"                              # Porta externa:interna
    volumes:
      - db_data:/var/lib/mysql                   # Persistência de dados
      - ./my.cnf:/etc/mysql/conf.d/my.cnf        # Configurações customizadas (opcional)

volumes:
  db_data:
    driver: local
